name: "Changelog Generator action"
description: "Generates changelog between commits"
author: "Petro Kurbatskyi"
inputs:
  currentTag:
    description: "Current tag"
    required: true
  previousTag:
    description: "Previous tag"
    required: true
  github_token:
    required: true
  jira_token:
    required: true
    description: "JIRA token to use to talk to JIRA"
outputs:
  changelog:
    description: "Changelog output"
runs:
  using: "docker"
  image: "docker://ghcr.io/ibexa/changelog-generator-action:v2.0.0"
